version: '3'
services:
  top.api:
    image: ghcr.io/denisjet/mytop-api/mytop-api:latest
    container_name: mytop-api
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./.env:/mytop-api/.env