version: '3'
services:
  top.api:
    image: docker pull ghcr.io/denisjet/mytop-api/mytop-api:latest
    container_name: mytop-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env